### ISSUE TITLE
Can't import with browserify and babel

### ISSUE THREAD

**Issue by DustinJSilk** [Sinova/Collisions#14]
Im trying desperately to import this package but can't seem to get it to work.

Installing from npm and requiring the package as I would any other package throws this error:
`
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
`

I then dug around for a few hours with babel, browserify, grunt-browserify, and did a lot of research. It just seems as though using .mjs files isn't that supported yet?

I then tried switching over to rollup however rollup had problems with most other libraries (fixing one, broke another). So i gave up on that. Babel it is.

I then tried setting this package as a git submodule, and then importing it relative to my code. 
Brilliant!
But babel still didn't like the .mjs files.
So I created aliases for them all so hopefully names wouldnt mattter. I still couldn't get them to work.

Next i tried adding a grunt task to copy all the files to .js. The problem being that you're referencing the relative files with extensions. So that solution along with the aliases still don't work.

Is there any way i can get this to work without having to fork the repo? I think it would need to support standard commonjs imports.

**Comment by GrosSacASac** [comment]
Hi would you mind sharing what you have done so far so that it is easier to help you.

In the meantime make sure all your files are .mjs (for node.js)
all your scripts in the browser are `<script type="module" src="..."></script>`

**Comment by DustinJSilk** [comment]
Thanks for a speedy response!

Im trying to compile it down into a single minified file to keep support for slightly older browsers and for quicker loadings, so i won't be able to use `<script type="module" src="..."></script>` unfortunately. And im using quite a few other node packages that aren't using ES6 imports so i wont be able to make them all .mjs.

My setup uses ES6 modules for all my frontend code. Then using babel, it gets compiled down to ES2015 with nodes standard CommonJS style imports / exports. And finally browserify puts compiles each separate module into a single file.

A little more digging around shows that [it is possible to support both the CommonJS and the latest ESM style exports](https://stackoverflow.com/a/46900211/2050141). However it might require duplicating files with a script of sorts.
The comment below that showed[ this project ](https://github.com/dandv/local-iso-dt)which managed to transpile the ESM code.

**Comment by GrosSacASac** [comment]
> My setup uses ES6 modules for all my frontend code

can you show your import statement ?

**Comment by silkphntm** [comment]
So does mine. Heres an example of my import statements:

```javascript
// These two are third party npm modules
import * as PIXI from 'pixi.js'
import {float, pick} from 'random-ext';

import {Ai, Speed} from '../car/ai';
import {Player} from '../car/player';

import Camera from '../renderer/camera';
import Road from './road';
import config from '../config';
```

These all work.

**Comment by DustinJSilk** [comment]
I've just forked your repository and added a quick compile script that should support both es6 and commonjs import statements: https://github.com/DustinJSilk/Collisions

(Using my other github account)

**Comment by GrosSacASac** [comment]
The problem seems to come from package.json, which is miss-configured, from the rollup docs:

> To make sure your ES6 modules are immediately usable by tools that work with CommonJS such as Node.js and webpack, you can use Rollup to compile to UMD or CommonJS format, and then point to that compiled version with the main property in your package.json file. If your package.json file also has a module field, ES6-aware tools like Rollup and webpack 2 will import the ES6 module version directly.

Conclusion :
In package.json

```
"main": "should be empty or have commonjs export"
"module": "should point to the previous main"
```

**Comment by nenjack** [comment]
@DustinJSilk is there any difference from https://www.npmjs.com/package/detect-collisions ??
