### ISSUE TITLE
Collisions not working when browser tab changes

### ISSUE THREAD

**Issue by yojona** [Sinova/Collisions#25]
When I change the browser tab, no collisions are detected, any ideas how to fix it?

gif: 
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/13840865/113496432-5f5bbc80-94ae-11eb-9ee4-8242c7835668.gif)

**Comment by GrosSacASac** [comment]
It probably has to do with the fact that browser slow down setInterval and requestAnimationFrame and others for inactive tabs.
I recommend to pause the game when the tab is inactive.

```
document.addEventListener(`visibilitychange`, function () {
    if (document.hidden) {
        pause();
    }
});
```

**Comment by yojona** [comment]
In case someone else have the same problem:

if I doa simple if/else the result is the same, I had to add a delay of 100ms before resuming the game again to avoid this problem.

thanks @GrosSacASac 


```javascript
const delay = ms => new Promise(res => setTimeout(res, ms));

document.addEventListener('visibilitychange', async () => {
  if (document.hidden) {
    setPause(true);
  } else {
    await delay(100)
    setPause(false)
  }
});
```
