### ISSUE TITLE
Declaration file

### ISSUE THREAD

**Issue by kefniark** [Sinova/Collisions#6]
I'm using this library with typescript, and to have types and Autocomplete, I wrote a [declaration file](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html) (mostly based on your nice jsdoc).

I just would like to know your preference:
* Can I add this declaration file to this repository and add a new field in package.json :
```json
   "types": "collisions.d.ts",
```
* Or should I keep this declaration file out of this repository and publish it separately to https://github.com/DefinitelyTyped/

**Comment by ShimShamSam** [comment]
Sure, submit a pull request. I don't use Typescript so I've never had to deal with declaration files.
